name: Deploy SoilSense

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "12345678" ssh -o StrictHostKeyChecking=no root@82.112.226.47 << 'EOF'
            cd ~/SoilSense-Soil-Monitoring-System
            git pull
            npm install
           pm2 restart soilease --update-env || pm2 start npm --name soilease -- start -- --port=8000 --host=0.0.0.0
          EOF
